AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pjinsights-profileclassifier-lambda

  Sample SAM Template for pjinsights-profileclassifier-lambda

Resources:
  ProfileClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ProfileClassifierLambda
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Timeout: 10
      Events:
        ProfileClassifierApiPost:
          Type: Api
          Properties:
            Path: /classify
            Method: post

Outputs:
  ProfileClassifierApi:
    Description: API Gateway endpoint URL for Prod stage for ProfileClassifier function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classify/"
    Export:
      Name: ProfileClassifierApi
  ProfileClassifierFunction:
    Description: ProfileClassifier Lambda Function ARN
    Value: !GetAtt ProfileClassifierFunction.Arn
  ProfileClassifierFunctionIamRole:
    Description: Implicit IAM Role created for ProfileClassifier function
    Value: !GetAtt ProfileClassifierFunction.Arn
